# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ratom-instructure}
  s.version = "0.6.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peerworks", "Sean Geoghegan", "Jacob Fugal"]
  s.date = %q{2011-07-13}
  s.description = %q{A fast Atom Syndication and Publication API based on libxml}
  s.email = %q{seangeo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "lib/atom.rb",
    "lib/atom/configuration.rb",
    "lib/atom/pub.rb",
    "lib/atom/version.rb",
    "lib/atom/xml/parser.rb",
    "ratom.gemspec",
    "spec/app/member_entry.atom",
    "spec/app/service.xml",
    "spec/app/service_xml_base.xml",
    "spec/atom/pub_spec.rb",
    "spec/atom_spec.rb",
    "spec/conformance/baseuri.atom",
    "spec/conformance/divtest.atom",
    "spec/conformance/linktests.xml",
    "spec/conformance/nondefaultnamespace-baseline.atom",
    "spec/conformance/nondefaultnamespace-xhtml.atom",
    "spec/conformance/nondefaultnamespace.atom",
    "spec/conformance/ordertest.xml",
    "spec/conformance/title/html-cdata.atom",
    "spec/conformance/title/html-entity.atom",
    "spec/conformance/title/html-ncr.atom",
    "spec/conformance/title/text-cdata.atom",
    "spec/conformance/title/text-entity.atom",
    "spec/conformance/title/text-ncr.atom",
    "spec/conformance/title/xhtml-entity.atom",
    "spec/conformance/title/xhtml-ncr.atom",
    "spec/conformance/unknown-namespace.atom",
    "spec/conformance/xmlbase.atom",
    "spec/fixtures/complex_single_entry.atom",
    "spec/fixtures/created_entry.atom",
    "spec/fixtures/entry.atom",
    "spec/fixtures/entry_with_custom_extensions.atom",
    "spec/fixtures/entry_with_simple_extensions.atom",
    "spec/fixtures/entry_with_single_custom_extension.atom",
    "spec/fixtures/multiple_entry.atom",
    "spec/fixtures/simple_single_entry.atom",
    "spec/fixtures/with_stylesheet.atom",
    "spec/paging/first_paged_feed.atom",
    "spec/paging/last_paged_feed.atom",
    "spec/paging/middle_paged_feed.atom",
    "spec/property.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/lukfugl/ratom}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Atom Syndication and Publication API}
  s.test_files = [
    "spec/atom/pub_spec.rb",
    "spec/atom_spec.rb",
    "spec/property.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<libxml-ruby>, [">= 1.1.2"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<libxml-ruby>, [">= 1.1.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<libxml-ruby>, [">= 1.1.2"])
  end
end

